[package]
name = "explorer"
version = "0.1.0"
edition = "2021"

[dependencies]
kibi = { path = "../.." }
minifb = "0.24.0"
raqote = { version = "0.8.2", default-features = false }
fontdue = "0.7.2"
lru = "0.10.0"
ordered-float = "3.4.0"
